apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.clustername }}
  namespace: {{ .Values.namespace }}
spec:
  clusterNetwork:
    pods:
      {{- with .Values.cluster.podsCidr }}
      cidrBlocks:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: {{ .Values.eksControlPlane.eksname }}
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: {{ .Values.eksControlPlane.eksname }}