apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ .Values.eksManagedNodeGroup.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterName: {{ .Values.cluster.clustername }}
  replicas: {{ .Values.eksManagedNodeGroup.replicas }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ .Values.cluster.clustername }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: {{ .Values.eksManagedNodeGroup.name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: {{ .Values.eksManagedNodeGroup.name }}
  namespace: {{ .Values.namespace }}
spec:
  amiVersion: {{ .Values.eksManagedNodeGroup.amiVersion }}
  availabilityZones:
    - "us-east-1a"
    - "us-east-1b"
  diskSize: 10
  eksNodegroupName: mediumgroup
  instanceType: t3.medium
  remoteAccess:
    sshKeyName: 20221104clusterapi