apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: managed-first
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: managed-first-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: managed-first-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: managed-first-control-plane
  namespace: default
spec:
  region: us-east-1
  sshKeyName: 20221104clusterapi
  version: v1.22.9
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: managed-first-pool-0
  namespace: default
spec:
  clusterName: managed-first
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: managed-first
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: managed-first-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: managed-first-pool-0
  namespace: default
spec: {}
